# reused blocks
deploy_block: &deploy_block
  image: opensuse
  commands:
    - echo 'deploy block'

condition_env_test2:
  when:
    branch: env/test2
    event: push
# reused blocks end

workspace:
  base: /project/dronetest
  path: ${DRONE_BRANCH}

clone:
  git:
    image: plugins/git

pipeline:
  test:
    image: opensuse
    commands:
      - echo test

  env_test1:
    image: opensuse
    when:
      branch: env/test1
      event: push
    commands:
      - pwd
      - echo ${DRONE_BRANCH}
      - ls -la

  deploy_test:
      <<: *deploy_block
      <<: *condition_env_test2

  deploy_master:
      <<: *deploy_block
      when:
        branch: master
        event: deployment
        environment: all
